site_name: Installation Manuals
site_url: https://docs.trikdis.com
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.png
  font: false
  palette:
    primary: custom
  features:
  - navigation.instant
  - navigation.expand
  - search.suggest
  - search.highlight
nav:
- Home: index.md
- English:
  - Communicators:
    - Cellular:
      - GT Cellular Communicator: en/alarm-communicators/gt-cellular/index.md
      - GT+ Cellular Communicator: en/alarm-communicators/gt-plus-cellular/index.md
    - Dual-path:
      - GET Cellular Communicator: en/alarm-communicators/get-cellular/index.md
  - Control Panels:
    - Security control panel FLEXi SP3: en/control-panels/sp3/index.md
  - Gate Controllers:
    - GATOR Cellular Gate Controller: en/gate-controllers/gator/index.md
    - GATOR WiFi Gate Controller: en/gate-controllers/gator-wifi/index.md
- Lithuanian:
  - Komunikatoriai:
    - Mobilaus ryšio:
      - GT GSM komunikatorius: lt/alarm-communicators/gt-cellular/index.md
      - GT+ GSM komunikatorius: lt/alarm-communicators/gt-plus-cellular/index.md
      - GSM komunikatorius G16: lt/alarm-communicators/g16/index.md
      - GSM komunikatorius G16T: lt/alarm-communicators/g16t/index.md
    - Dvigubas Kanalas:
      - GSM/Ethernet komunikatorius GET: lt/alarm-communicators/get-cellular/index.md
    - Priešgaisrinėms centralėms:
      - Priešgaisrinės centralės komunikatorius FIRECOM: lt/alarm-communicators/firecom/index.md
      - Priešgaisrinės centralės GSM komunikatorius G17F: lt/alarm-communicators/g17f/index.md
    - Ethernet:
      - Ethernet komunikatorius E16: lt/alarm-communicators/e16/index.md
      - Ethernet komunikatorius E16T: lt/alarm-communicators/e16t/index.md
    - UHF radijo bangomis:
      - Siųstuvas T16: lt/alarm-communicators/t16/index.md
  - Apsaugos centrelės:
    - Apsaugos centralė “FLEXi” SP3: lt/control-panels/sp3/index.md
    - GSM apsaugos centralė CG17: lt/control-panels/cg17/index.md
  - Valdikliai:
    - Gator: lt/gate-controllers/gator/index.md
    - Gator Wifi: lt/gate-controllers/gator-wifi/index.md
- Spanish:
  - Comunicadores:
    - Celular:
      - GT Comunicador: es/alarm-communicators/gt-cellular/index.md
      - GT+ Comunicador: es/alarm-communicators/gt-plus-cellular/index.md
    - Comunicación de Doble Vía:
      - Comunicador GET: es/alarm-communicators/get-cellular/index.md
  - Paneles de control:
    - Panel de control FLEXi SP3: es/control-panels/sp3/index.md
  - Controladores:
    - Gator: es/gate-controllers/gator/index.md
    - Gator Wifi: es/gate-controllers/gator-wifi/index.md
extra_css:
- stylesheets/base.user.css
- stylesheets/numbered-headings.css
extra_javascript:
- javascripts/redirect-trailing-slash.js
plugins:
- search:
    lang:
    - en
    - lt
    - es
    separator: '[\s\-]+'
- add-number:
    order: 2
    strict_mode: false
    excludes:
    - index.md
- redirects:
    redirect_maps: {}
- minify:
    minify_html: true
    minify_js: true
    minify_css: true
    htmlmin_opts:
      remove_comments: true
markdown_extensions:
- attr_list
- admonition
- sane_lists
- tables
- pymdownx.details
- pymdownx.superfences
- markdown_callouts
- toc:
    permalink: true
    permalink_title: Link to this section
