site_name: Installation Manuals
site_url: https://docs.trikdis.com
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.png
  font: false
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: custom
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: custom
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  features:
  - navigation.instant
  - navigation.sections
  - navigation.top
  - navigation.expand
  - content.code.copy
  - search.share
  - search.suggest
  - search.highlight
nav:
- Home: index.md
- English:
  - Communicators:
    - Cellular:
      - GT Cellular Communicator: en/alarm-communicators/gt-cellular/index.md
      - GT+ Cellular Communicator: en/alarm-communicators/gt-plus-cellular/index.md
      - Cellular communicator G16: en/alarm-communicators/g16/index.md
      - Cellular communicator G16T: en/alarm-communicators/g16t/index.md
    - Dual-path:
      - GET Cellular Communicator: en/alarm-communicators/get-cellular/index.md
    - For Fire Panels:
      - Communicator FireCom: en/alarm-communicators/firecom/index.md
      - Cellular communicator G17F: en/alarm-communicators/g17f/index.md
    - Ethernet:
      - Ethernet communicator E16: en/alarm-communicators/e16/index.md
      - Ethernet communicator E16T: en/alarm-communicators/e16t/index.md
    - Radio:
      - Transmitter T16: en/alarm-communicators/t16/index.md
  - Control Panels:
    - Security control panel FLEXi SP3: en/control-panels/sp3/index.md
    - Cellular security control panel CG17: en/control-panels/cg17/index.md
  - Gate Controllers:
    - GATOR Cellular Gate Controller: en/gate-controllers/gator/index.md
    - GATOR WiFi Gate Controller: en/gate-controllers/gator-wifi/index.md
  - Keypads:
    - Keypad SK-LCD Button: en/keypads/sk-lcd-button/index.md
    - Keypad SK-LED Button: en/keypads/sk-led-button/index.md
    - Keypad FLEXi SK LCD: en/keypads/flexi-sk-lcd/index.md
    - Keypad FLEXi SK LED: en/keypads/flexi-sk-led/index.md
- Lithuanian:
  - Komunikatoriai:
    - Mobilaus ryšio:
      - GT GSM komunikatorius: lt/alarm-communicators/gt-cellular/index.md
      - GT+ GSM komunikatorius: lt/alarm-communicators/gt-plus-cellular/index.md
      - GSM komunikatorius G16: lt/alarm-communicators/g16/index.md
      - GSM komunikatorius G16T: lt/alarm-communicators/g16t/index.md
    - Dvigubas Kanalas:
      - GSM/Ethernet komunikatorius GET: lt/alarm-communicators/get-cellular/index.md
    - Priešgaisrinėms centralėms:
      - Priešgaisrinės centralės komunikatorius FIRECOM: lt/alarm-communicators/firecom/index.md
      - Priešgaisrinės centralės GSM komunikatorius G17F: lt/alarm-communicators/g17f/index.md
    - Ethernet:
      - Ethernet komunikatorius E16: lt/alarm-communicators/e16/index.md
      - Ethernet komunikatorius E16T: lt/alarm-communicators/e16t/index.md
    - UHF radijo bangomis:
      - Siųstuvas T16: lt/alarm-communicators/t16/index.md
  - Apsaugos centrelės:
    - Apsaugos centralė “FLEXi” SP3: lt/control-panels/sp3/index.md
    - GSM apsaugos centralė CG17: lt/control-panels/cg17/index.md
  - Valdikliai:
    - Gator: lt/gate-controllers/gator/index.md
    - Gator Wifi: lt/gate-controllers/gator-wifi/index.md
  - Klaviatūros:
    - SK-LCD mygtukinė klaviatūra: lt/keypads/sk-lcd-button/index.md
    - SK-LED Button klaviatūra: lt/keypads/sk-led-button/index.md
    - Klaviatūra FLEXi SK LCD: lt/keypads/flexi-sk-lcd/index.md
    - Klaviatūra FLEXi SK LED: lt/keypads/flexi-sk-led/index.md
- Spanish:
  - Comunicadores:
    - Celular:
      - GT Comunicador: es/alarm-communicators/gt-cellular/index.md
      - GT+ Comunicador: es/alarm-communicators/gt-plus-cellular/index.md
      - Comunicador celular G16: es/alarm-communicators/g16/index.md
      - Comunicador celular G16T: es/alarm-communicators/g16t/index.md
    - Comunicación de Doble Vía:
      - Comunicador GET: es/alarm-communicators/get-cellular/index.md
    - Celular para Incendio:
      - Comunicador FireCom: es/alarm-communicators/firecom/index.md
      - Comunicador Celular G17F: es/alarm-communicators/g17f/index.md
    - Ethernet:
      - Comunicador Ethernet E16: es/alarm-communicators/e16/index.md
      - Comunicador Ethernet E16T: es/alarm-communicators/e16t/index.md
    - Banda de radio UHF:
      - Transmisor T16: es/alarm-communicators/t16/index.md
  - Paneles de control:
    - Panel de control FLEXi SP3: es/control-panels/sp3/index.md
    - Celular panel de control CG17: es/control-panels/cg17/index.md
  - Controladores:
    - Gator: es/gate-controllers/gator/index.md
    - Gator Wifi: es/gate-controllers/gator-wifi/index.md
  - Teclados:
    - Teclado SK-LCD Button: es/keypads/sk-lcd-button/index.md
    - Teclado SK-LED Button: es/keypads/sk-led-button/index.md
    - Teclado FLEXi SK LCD: es/keypads/flexi-sk-lcd/index.md
    - Teclado FLEXi SK LED: es/keypads/flexi-sk-led/index.md
- Russian:
  - Коммуникаторы:
    - GSM/GPRS:
      - GSM коммуникатор GT: ru/alarm-communicators/gt-cellular/index.md
      - GSM коммуникатор GT+: ru/alarm-communicators/gt-plus-cellular/index.md
      - GSM коммуникатор G16: ru/alarm-communicators/g16/index.md
      - GSM коммуникатор G16T: ru/alarm-communicators/g16t/index.md
    - Двойной Коммуникатор:
      - коммуникатор GET: ru/alarm-communicators/get-cellular/index.md
    - Для противопожарной охранной панели:
      - Коммуникатор FireCom: ru/alarm-communicators/firecom/index.md
      - GSM коммуникатор G17F: ru/alarm-communicators/g17f/index.md
    - Ethernet:
      - Ethernet коммуникатор E16: ru/alarm-communicators/e16/index.md
      - Ethernet модуль E16T: ru/alarm-communicators/e16t/index.md
    - UHF модули:
      - Радиопередатчик Т16: ru/alarm-communicators/t16/index.md
  - Панели управления:
    - Охранная панель FLEXi SP3: ru/control-panels/sp3/index.md
    - GSM oхранная панель CG17: ru/control-panels/cg17/index.md
  - Контроллеры:
    - Контроллер управления воротами GATOR: ru/gate-controllers/gator/index.md
    - Wi-Fi контроллер GATOR: ru/gate-controllers/gator-wifi/index.md
  - Клавиатуры:
    - Клавиатура SK-LCD Button: ru/keypads/sk-lcd-button/index.md
    - Клавиатура SK-LED Button: ru/keypads/sk-led-button/index.md
    - Клавиатура FLEXi SK LCD: ru/keypads/flexi-sk-lcd/index.md
extra:
  alternate:
  - name: English
    link: /en/
    lang: en
  - name: Lietuvių
    link: /lt/
    lang: lt
  - name: Español
    link: /es/
    lang: es
  - name: Русский
    link: /ru/
    lang: ru
  social:
  - icon: material/help-circle
    name: Support
    link: https://www.trikdis.com/support
  - icon: material/email-outline
    name: Contact Support
    link: mailto:support@trikdis.com
extra_css:
- stylesheets/base.user.css
- stylesheets/numbered-headings.css
extra_javascript:
- javascripts/redirect-trailing-slash.js
- javascripts/close-language-select.js
- javascripts/cycle-welcome.js
- javascripts/language-ui.js
plugins:
- search:
    lang:
    - en
    - lt
    - es
    - ru
    separator: '[\s\-]+'
- add-number:
    order: 2
    strict_mode: false
    excludes:
    - index.md
- redirects:
    redirect_maps: {}
- minify:
    minify_html: true
    minify_js: true
    minify_css: true
    htmlmin_opts:
      remove_comments: true
markdown_extensions:
- meta
- attr_list
- admonition
- sane_lists
- tables
- pymdownx.details
- pymdownx.superfences
- markdown_callouts
- toc:
    permalink: true
    permalink_title: Link to this section
