site_name: Installation Manuals
site_url: https://docs.trikdis.com
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.png
  font: false
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: custom
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: custom
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  features:
  - navigation.instant
  - navigation.sections
  - navigation.top
  - content.code.copy
  - search.share
  - search.suggest
  - search.highlight
nav: []

exclude_docs: |
  _NAVIGATION.md
  _temp/
  preview/

extra:
  alternate:
  - name: English
    link: /en/
    lang: en
  - name: Lietuvių
    link: /lt/
    lang: lt
  - name: Español
    link: /es/
    lang: es
  - name: Русский
    link: /ru/
    lang: ru
  social:
  - icon: material/help-circle
    name: Support
    link: https://www.trikdis.com/support
  - icon: material/email-outline
    name: Contact Support
    link: mailto:support@trikdis.com
extra_css:
- stylesheets/base.user.v2.css
- stylesheets/numbered-headings.css
extra_javascript:
- javascripts/redirect-trailing-slash.js
- javascripts/close-language-select.js
- javascripts/cycle-welcome.js
- javascripts/language-ui.js
- javascripts/mobile-toc-default.js
- javascripts/toc-active.js
- javascripts/lazy-images.js
plugins:
- i18n:
    docs_structure: folder
    fallback_to_default: true
    reconfigure_material: false
    languages:
    - locale: xx
      name: Home
      default: true
      build: true
      link: /
    - locale: en
      name: English
      build: true
      nav:
      - Home: index.md
      - Communicators:
        - Cellular:
          - GT/GT+/GET:
            - Quick setup GT/GT+/GET:
              - Paradox SP(+)/MG(+): alarm-communicators/cellular/quick-setup/paradox/index.md
              - DSC NEO HS2016: alarm-communicators/cellular/quick-setup/dsc neo hs/GT+ NEO HS2016 2026 01 07.md
              - DSC PC585: alarm-communicators/cellular/quick-setup/dsc pc/GT+ DSC PC585 2026 01 06.md
              - Honeywell Vista-48: alarm-communicators/cellular/quick-setup/honeywell vista/GT+ Honeywell vista 48 ENG 2026 01 07.md
              - Interlogix NX-4V2 / NX-6V2: alarm-communicators/cellular/quick-setup/interlogix nx-4v2 nx-6v2/GT+ Interlogix NX-4V2 NX-6V2 ENG 2026 01 07.md
              - Interlogix NX-8V2: alarm-communicators/cellular/quick-setup/interlogix nx-8v2/GT+ Interlogix NX-8V2 2026 01 07.md
            - GT: alarm-communicators/cellular/gt/index.md
            - GT+: alarm-communicators/cellular/gt-plus/index.md
            - GET: alarm-communicators/cellular/get/index.md
          - G16: alarm-communicators/cellular/g16/index.md
          - G16T: alarm-communicators/cellular/g16t/index.md
        - For Fire Panels:
          - FireCom: alarm-communicators/fire-panels/firecom/index.md
          - G17F: alarm-communicators/fire-panels/g17f/index.md
        - Ethernet:
          - E16: alarm-communicators/e16/index.md
          - E16T: alarm-communicators/e16t/index.md
        - Radio:
          - T16: alarm-communicators/t16/index.md
      - Control Panels:
        - FLEXi SP3: control-panels/sp3/index.md
        - CG17: control-panels/cg17/index.md
      - Gate Controllers:
        - GATOR: gate-controllers/gator/index.md
        - GATOR WiFi: gate-controllers/gator-wifi/index.md
      - Keypads:
        - Keypad SK-LCD Button: keypads/sk-lcd-button/index.md
        - Keypad SK-LED Button: keypads/sk-led-button/index.md
        - Keypad SK-LCD TouchPad: keypads/sk-lcd-touchpad/index.md
        - Keypad SK-LED TouchPad: keypads/sk-led-touchpad/index.md
        - Keypad FLEXi SK LCD: keypads/flexi-sk-lcd/index.md
        - Keypad FLEXi SK LED: keypads/flexi-sk-led/index.md
    - locale: lt
      name: Lietuvių
      build: true
      nav:
      - Home: index.md
      - Komunikatoriai:
        - Mobilaus ryšio:
          - GT: alarm-communicators/cellular/gt/index.md
          - GT+: alarm-communicators/cellular/gt-plus/index.md
          - GET: alarm-communicators/cellular/get/index.md
          - G16: alarm-communicators/cellular/g16/index.md
          - G16T: alarm-communicators/cellular/g16t/index.md
        - Priešgaisrinėms centralėms:
          - FIRECOM: alarm-communicators/fire-panels/firecom/index.md
          - G17F: alarm-communicators/fire-panels/g17f/index.md
        - Ethernet:
          - E16: alarm-communicators/e16/index.md
          - E16T: alarm-communicators/e16t/index.md
        - UHF radijo bangomis:
          - T16: alarm-communicators/t16/index.md
      - Apsaugos centrelės:
        - FLEXi SP3: control-panels/sp3/index.md
        - CG17: control-panels/cg17/index.md
      - Valdikliai:
        - Gator: gate-controllers/gator/index.md
        - Gator Wifi: gate-controllers/gator-wifi/index.md
      - Klaviatūros:
        - SK-LCD mygtukinė klaviatūra: keypads/sk-lcd-button/index.md
        - SK-LED Button klaviatūra: keypads/sk-led-button/index.md
        - SK-LCD TouchPad klaviatūra: keypads/sk-lcd-touchpad/index.md
        - SK-LED TouchPad klaviatūra: keypads/sk-led-touchpad/index.md
        - Klaviatūra FLEXi SK LCD: keypads/flexi-sk-lcd/index.md
        - Klaviatūra FLEXi SK LED: keypads/flexi-sk-led/index.md
    - locale: es
      name: Español
      build: true
      nav:
      - Home: index.md
      - Comunicadores:
        - Celular:
          - GT: alarm-communicators/cellular/gt/index.md
          - GT+: alarm-communicators/cellular/gt-plus/index.md
          - GET: alarm-communicators/cellular/get/index.md
          - G16: alarm-communicators/cellular/g16/index.md
          - G16T: alarm-communicators/cellular/g16t/index.md
        - Celular para Incendio:
          - FireCom: alarm-communicators/fire-panels/firecom/index.md
          - G17F: alarm-communicators/fire-panels/g17f/index.md
        - Ethernet:
          - E16: alarm-communicators/e16/index.md
          - E16T: alarm-communicators/e16t/index.md
        - Banda de radio UHF:
          - T16: alarm-communicators/t16/index.md
      - Paneles de control:
        - FLEXi SP3: control-panels/sp3/index.md
        - CG17: control-panels/cg17/index.md
      - Controladores:
        - Gator: gate-controllers/gator/index.md
        - Gator Wifi: gate-controllers/gator-wifi/index.md
      - Teclados:
        - Teclado SK-LCD Button: keypads/sk-lcd-button/index.md
        - Teclado SK-LED Button: keypads/sk-led-button/index.md
        - Teclado SK-LCD TouchPad: keypads/sk-lcd-touchpad/index.md
        - Teclado SK-LED TouchPad: keypads/sk-led-touchpad/index.md
        - Teclado FLEXi SK LCD: keypads/flexi-sk-lcd/index.md
        - Teclado FLEXi SK LED: keypads/flexi-sk-led/index.md
    - locale: ru
      name: Русский
      build: true
      nav:
      - Home: index.md
      - Коммуникаторы:
        - GSM/GPRS:
          - GT: alarm-communicators/cellular/gt/index.md
          - GT+: alarm-communicators/cellular/gt-plus/index.md
          - GET: alarm-communicators/cellular/get/index.md
          - G16: alarm-communicators/cellular/g16/index.md
          - G16T: alarm-communicators/cellular/g16t/index.md
        - Для противопожарной охранной панели:
          - FireCom: alarm-communicators/fire-panels/firecom/index.md
          - G17F: alarm-communicators/fire-panels/g17f/index.md
        - Ethernet:
          - E16: alarm-communicators/e16/index.md
          - E16T: alarm-communicators/e16t/index.md
        - UHF модули:
          - T16: alarm-communicators/t16/index.md
      - Панели управления:
        - FLEXi SP3: control-panels/sp3/index.md
        - CG17: control-panels/cg17/index.md
      - Контроллеры:
        - GATOR: gate-controllers/gator/index.md
        - GATOR WiFi: gate-controllers/gator-wifi/index.md
      - Клавиатуры:
        - Клавиатура SK-LCD Button: keypads/sk-lcd-button/index.md
        - Клавиатура SK-LED Button: keypads/sk-led-button/index.md
        - Клавиатура SK-LCD TouchPad: keypads/sk-lcd-touchpad/index.md
        - Клавиатура FLEXi SK LCD: keypads/flexi-sk-lcd/index.md
- search:
    lang:
    - en
    - lt
    - es
    - ru
    separator: '[\s\-]+'
- add-number:
    order: 2
    strict_mode: false
    excludes:
    - index.md
- redirects:
    redirect_maps:
      index.md: en/index.md
- minify:
    minify_html: true
    minify_js: true
    minify_css: true
    htmlmin_opts:
      remove_comments: true
hooks:
- mkdocs_hooks.py
markdown_extensions:
- meta
- attr_list
- admonition
- sane_lists
- tables
- pymdownx.details
- pymdownx.superfences
- markdown_callouts
- toc:
    permalink: true
    permalink_title: Link to this section
