site_name: Installation Manuals
site_url: https://docs.trikdis.com
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.png
  font: false
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: custom
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: custom
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  features:
  - navigation.instant
  - navigation.sections
  - navigation.top
  - navigation.expand
  - toc.integrate
  - content.code.copy
  - search.share
  - search.suggest
  - search.highlight
nav:
- Home: index.md
- English:
  - Overview: en/index.md
  - Communicators:
    - Cellular:
      - Quick setup GT/GT+/GET:
        - Paradox SP(+)/MG(+): en/alarm-communicators/cellular/quick-setup/paradox/index.md
      - GT/GT+/GET manuals:
        - GT Cellular Communicator: en/alarm-communicators/cellular/gt/index.md
        - GT+ Cellular Communicator: en/alarm-communicators/cellular/gt-plus/index.md
        - GET Cellular Communicator: en/alarm-communicators/dual-path/get/index.md
      - Cellular communicator G16: en/alarm-communicators/g16/index.md
      - Cellular communicator G16T: en/alarm-communicators/g16t/index.md
    - Dual-path:
      - GET Cellular Communicator: en/alarm-communicators/dual-path/get/index.md
    - For Fire Panels:
      - Communicator FireCom: en/alarm-communicators/fire-panels/firecom/index.md
      - Cellular communicator G17F: en/alarm-communicators/fire-panels/g17f/index.md
    - Ethernet:
      - Ethernet communicator E16: en/alarm-communicators/e16/index.md
      - Ethernet communicator E16T: en/alarm-communicators/e16t/index.md
    - Radio:
      - Transmitter T16: en/alarm-communicators/t16/index.md
  - Control Panels:
    - Security control panel FLEXi SP3: en/control-panels/sp3/index.md
    - Cellular security control panel CG17: en/control-panels/cg17/index.md
  - Gate Controllers:
    - GATOR Cellular Gate Controller: en/gate-controllers/gator/index.md
    - GATOR WiFi Gate Controller: en/gate-controllers/gator-wifi/index.md
  - Lithuanian:
    - Apžvalga: lt/index.md
    - Komunikatoriai:
      - Mobilaus ryšio:
        - GT GSM komunikatorius: lt/alarm-communicators/cellular/gt/index.md
        - GT+ GSM komunikatorius: lt/alarm-communicators/cellular/gt-plus/index.md
        - GSM komunikatorius G16: lt/alarm-communicators/g16/index.md
        - GSM komunikatorius G16T: lt/alarm-communicators/g16t/index.md
      - Dvigubas Kanalas:
        - GSM/Ethernet komunikatorius GET: lt/alarm-communicators/dual-path/get/index.md
      - Priešgaisrinėms centralėms:
        - Priešgaisrinės centralės komunikatorius FIRECOM: lt/alarm-communicators/fire-panels/firecom/index.md
        - Priešgaisrinės centralės GSM komunikatorius G17F: lt/alarm-communicators/fire-panels/g17f/index.md
    - Ethernet:
      - Ethernet komunikatorius E16: lt/alarm-communicators/e16/index.md
      - Ethernet komunikatorius E16T: lt/alarm-communicators/e16t/index.md
    - UHF radijo bangomis:
      - Siųstuvas T16: lt/alarm-communicators/t16/index.md
  - Apsaugos centrelės:
    - Apsaugos centralė FLEXi SP3: lt/control-panels/sp3/index.md
    - GSM apsaugos centralė CG17: lt/control-panels/cg17/index.md
  - Valdikliai:
    - Gator: lt/gate-controllers/gator/index.md
    - Gator Wifi: lt/gate-controllers/gator-wifi/index.md
  - Spanish:
    - Visión general: es/index.md
    - Comunicadores:
      - Celular:
        - GT Comunicador: es/alarm-communicators/cellular/gt/index.md
        - GT+ Comunicador: es/alarm-communicators/cellular/gt-plus/index.md
        - Comunicador celular G16: es/alarm-communicators/g16/index.md
        - Comunicador celular G16T: es/alarm-communicators/g16t/index.md
      - Comunicación de Doble Vía:
        - Comunicador GET: es/alarm-communicators/dual-path/get/index.md
      - Celular para Incendio:
        - Comunicador FireCom: es/alarm-communicators/fire-panels/firecom/index.md
        - Comunicador Celular G17F: es/alarm-communicators/fire-panels/g17f/index.md
    - Ethernet:
      - Comunicador Ethernet E16: es/alarm-communicators/e16/index.md
      - Comunicador Ethernet E16T: es/alarm-communicators/e16t/index.md
    - Banda de radio UHF:
      - Transmisor T16: es/alarm-communicators/t16/index.md
  - Paneles de control:
    - Panel de control FLEXi SP3: es/control-panels/sp3/index.md
    - Celular panel de control CG17: es/control-panels/cg17/index.md
  - Controladores:
    - Gator: es/gate-controllers/gator/index.md
    - Gator Wifi: es/gate-controllers/gator-wifi/index.md
  - Russian:
    - Обзор: ru/index.md
    - Коммуникаторы:
      - GSM/GPRS:
        - GSM коммуникатор GT: ru/alarm-communicators/cellular/gt/index.md
        - GSM коммуникатор GT+: ru/alarm-communicators/cellular/gt-plus/index.md
        - GSM коммуникатор G16: ru/alarm-communicators/g16/index.md
        - GSM коммуникатор G16T: ru/alarm-communicators/g16t/index.md
      - Двойной Коммуникатор:
        - коммуникатор GET: ru/alarm-communicators/dual-path/get/index.md
      - Для противопожарной охранной панели:
        - Коммуникатор FireCom: ru/alarm-communicators/fire-panels/firecom/index.md
        - GSM коммуникатор G17F: ru/alarm-communicators/fire-panels/g17f/index.md
    - Ethernet:
      - Ethernet коммуникатор E16: ru/alarm-communicators/e16/index.md
      - Ethernet модуль E16T: ru/alarm-communicators/e16t/index.md
    - UHF модули:
      - Радиопередатчик Т16: ru/alarm-communicators/t16/index.md
  - Панели управления:
    - Охранная панель FLEXi SP3: ru/control-panels/sp3/index.md
    - GSM oхранная панель CG17: ru/control-panels/cg17/index.md
  - Контроллеры:
    - Контроллер управления воротами GATOR: ru/gate-controllers/gator/index.md
    - Wi-Fi контроллер GATOR: ru/gate-controllers/gator-wifi/index.md
extra:
  alternate:
  - name: English
    link: /en/
    lang: en
  - name: Lietuvių
    link: /lt/
    lang: lt
  - name: Español
    link: /es/
    lang: es
  - name: Русский
    link: /ru/
    lang: ru
  social:
  - icon: material/help-circle
    name: Support
    link: https://www.trikdis.com/support
  - icon: material/email-outline
    name: Contact Support
    link: mailto:support@trikdis.com
extra_css:
- stylesheets/base.user.css
- stylesheets/numbered-headings.css
extra_javascript:
- javascripts/redirect-trailing-slash.js
- javascripts/close-language-select.js
- javascripts/cycle-welcome.js
- javascripts/language-ui.js
- javascripts/mobile-toc-toggle.js
plugins:
- search:
    lang:
    - en
    - lt
    - es
    - ru
    separator: '[\s\-]+'
- add-number:
    order: 2
    strict_mode: false
    excludes:
    - index.md
- redirects:
    redirect_maps: {}
- minify:
    minify_html: true
    minify_js: true
    minify_css: true
    htmlmin_opts:
      remove_comments: true
markdown_extensions:
- meta
- attr_list
- admonition
- sane_lists
- tables
- pymdownx.details
- pymdownx.superfences
- markdown_callouts
- toc:
    permalink: true
    permalink_title: Link to this section
